### PR TITLE
Replace coveralls with codecov

### LINKED ISSUE #70: replace coveralls with codecov
follow up for https://github.com/semantic-release/condition-travis/pull/68

### PR DESCRIPTION
**Pull request by vanduynslagerp**
Fix #70

@gr2m Can you make the codecov config (add repo to codecov, get the token and add it to Travis) or make me admin so I can do it? Thanks !

We should do that before merging this PR, so we can test everything works by having Codecov reporting on this PR.

### CODE REVIEW

**Comment by gr2m** [comment]
I’ve made you admin for this repo. I don’t think we need to configure a token for public repos when tests are running on travis

**Comment by gr2m** [comment]
> Repository tokens are required for (a) all private repos, (b) public repos not using Travis-CI, CircleCI or AppVeyor. 

https://github.com/codecov/example-node#nodejs--javascript-example

**Comment by vanduynslagerp** [comment]
Ahhh...that's great ! I didn't know. That makes configuration even easier.

**Comment by vanduynslagerp** [comment]
I just want to make sure the PR status is reported properly before merging

**Comment by vanduynslagerp** [comment]
We have to enable codecov Github app with this link: https://github.com/organizations/semantic-release/settings/installations/53605

For some reason I get a 404. Same issue with Greenkeeper by the way.

**Comment by gr2m** [comment]
Yeah there is something wonky, I’ve experienced it in other organisations where I was added recently. I’ve enabled codecov for the rpo

**Pull request merged**
